### ISSUE TITLE
RAG Feature: Expose features of RAG query to UI - Tracking Issue

### ISSUE THREAD

**Issue by rmusser01** [rmusser01/tldw_server#218]
Currently the RAG system has 0 knobs and levers for managing it from the UI.

Fix that, and expose every option for ingestion + search as things develop.

- [x] Keyword Search
- [ ] Chunking options on ingestion of vector embeddings
- [ ] Top-k for BM25 search
- [x] Query Re-writing
- [ ] Top-k amount for Vector results
- [ ] Re-ranking
- [ ] Multi-Database Selection
- [ ] Multi-Item, no keyword selection
