### ISSUE TITLE
Feature Tracker: Evaluation Benchmarks

### ISSUE THREAD

**Issue by rmusser01** [rmusser01/tldw_server#237]
Title.

Benchmarks:
Evaluation Methodologies
- [x] G-Eval
- [ ] QAG

Coding Ability
- [ ] Aider Benchmark
- [ ] CodeMMLU

Confabulation Rate
- [ ] TruthfulQA
- [ ] f

Context Length
- [ ] Ruler
- [ ] InfiniteBench
- [ ] Babilong
- [ ] LongICLBench
- [ ] HelloBench
- [ ] Snorkel Working Memory Test

Creative Writing
- [ ] EQ Bench
- [ ] f

Pop Culture
- [ ] f

Reasoning
- [ ] MMLU Pro
- [ ] ARC public

Role Playing
- Conversational Relevancy
- Role Adherence
- Knowledge Retention
- Conversation Competeness

Summarization
- [ ] DeepEval
- [ ] Salesforce
- [ ] F

Tool Calling
- [ ] DeepEval
- [ ] Berkeley Function Calling https://gorilla.cs.berkeley.edu/leaderboard.html
- [ ] ToolSandbox https://arxiv.org/html/2408.04682v1

Toxicity Testing 
- [ ] DeepEval
- [ ] f

Vibes
- [ ] AidanBench
- [ ] f

**Comment by rmusser01** [comment]
https://www.microsoft.com/en-us/research/blog/eureka-evaluating-and-understanding-progress-in-ai/

**Comment by rmusser01** [comment]
https://github.com/Quehry/HelloBench
https://arxiv.org/abs/2409.16191

**Comment by rmusser01** [comment]
https://eqbench.com/creative_writing.html

**Comment by rmusser01** [comment]
https://codecompass00.substack.com/p/llm-evaluation-leaderboards

**Comment by rmusser01** [comment]
https://ai.plainenglish.io/how-to-evaluate-fluency-in-llms-and-why-g-eval-doesnt-work-3635298e9a43?gi=86d2f43c09e8

**Comment by rmusser01** [comment]
https://arxiv.org/abs/2410.01999

**Comment by rmusser01** [comment]
https://github.com/tianyi-lab/BenTo

**Comment by rmusser01** [comment]
https://www.microsoft.com/en-us/research/publication/eureka-evaluating-and-understanding-large-foundation-models/

**Comment by rmusser01** [comment]
https://github.com/lechmazur/deception

**Comment by rmusser01** [comment]
https://github.com/aidanmclaughlin/Aidan-Bench

**Comment by rmusser01** [comment]
```
Using an LLM as a Response Judge

Some metrics cannot be defined objectively and are particularly useful for more subjective or complex criteria. We care about correctness, faithfulness, and relevance.

    Answer Correctness - Is the generated answer correct compared to the reference and thoroughly answers the user's query?
    Answer Relevancy - Is the generated answer relevant and comprehensive?
    Answer Factfulness - Is the generated answer factually consistent with the context document?
```
